# values file for example with ct

ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: le-test
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: Prefix
  tls:
   - secretName: chart-example-tls
     hosts:
       - chart-example.local
